# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/setup.md
fos_elastica:
    clients:
        default: { url: '%env(ELASTICSEARCH_URL)%' }
    indexes:
        transcription_chunks:
            properties:
                embedding:
                    type: dense_vector
                    dims: 1536
                    index: true
                    similarity: cosine
            persistence:
                driver: orm
                model: App\Entity\TranscriptionChunk
                provider: ~
                finder: ~
                listener:
                    insert: true
                    update: true
                    delete: true
