services:
  caddy:
    volumes:
      - ./docker/config/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./:/var/www/html
    ports:
      - "8080:80"
    extra_hosts:
      - host.docker.internal:host-gateway
  php:
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./:/var/www/html
      - ./docker/config/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./docker/config/supervisor/supervisord.conf:/etc/supervisor/supervisord.conf:ro
      - ./docker/config/supervisor/supervisord-programs.conf:/etc/supervisor/conf.d/app.conf:ro
  database:
    ports:
      - "5432:5432"
